## Server Properties
server:
  port: 8080
  server.compression.enabled: true

## Hibernate Logging
logging.level.org.hibernate.SQL: DEBUG

## App Properties
app:
  jwtSecret: JWTSecretKey
  jwtExpirationInMs: 604800

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
