## Server Properties
server:
  port: 5000
  server.compression.enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring:
#  datasource:
#    url: jdbc:mysql://54.180.14.6:3306/anything?useSSL=false
#    username: admin
#    password: 1234
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.ddl-auto: update
#    show-sql: true

## Hibernate Logging
logging.level.org.hibernate.SQL: DEBUG

## App Properties
app:
  jwtSecret: JWTSecretKey
  jwtExpirationInMs: 604800

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
